full_name = "Liliana Carrillo"
description = "Social and Digital Entrepreneur and Researcher, proud ThreeFold Ambassador"
why_threefold = "When water does not flow it gets foul. Other resources are for me like water.  When resources do not flow they also 'foul', they get concentrated in the hands of a few, leading to the concentration of power.  I am part of the ThreeFold movement because the team is creating technology that enables resources to flow, distribute them and decentralize them.  Most of my work is related to the decentralization of power at different levels, starting from individual work to global movements. I am contributing to a global shift and decentralization of data storage, decision power, business, education to mention some.  Join the ThreeFold movement!"
function = "R&D Manager and HR"
rank = 0
project_ids = [1]
contribution_ids = [2]
nationality = "World citizen, Colombian/Spanish living in Belgium"
