full_name = "Ashraf Fouda"
description = "Software Engineer with passion in new technologies, love every thing that is realy new and challenging."
why_threefold = ""
function = "Engineer"
rank = 0
project_ids = [1,8]
contribution_ids = [6,6]
nationality = "Egyptian"
