full_name = "Jan de Landtsheer"
description = "Head of Research & Development"
why_threefold = ""
function = "Head of Research & Development"
rank = 0
project_ids = [2]
contribution_ids = [6]
nationality = "Belgian"
