full_name = "John Kheir"
description = "John has started his carrer working for GIG, He has now about 3 years of experience in Cloud Computing software. Currently John is working as a Automation Software Testing Engineer for TFtech, working on writinig automation testsuites for all the project components."
why_threefold = ""
function = ""
rank = 0
project_ids = [1,8]
contribution_ids = [6,6]
nationality = "Egyptian"
