full_name = "Rana Hassan"
description = "Rana is an enthusiastic Computer Engineer with a passion in learning and development. She enjoys a good cup of coffee and exploring new technologies."
why_threefold = ""
function = "Engineer"
rank = 0
project_ids = [1,8]
contribution_ids = [6,3]
nationality = "Egyptian"
