full_name = "Muhamad Azmy"
description = "A highly driven IT professional, and a perfection seeker."
why_threefold = ""
function = ""
rank = 0
project_ids = [1,8]
contribution_ids = [6,6]
nationality = "Egyptian"
