full_name = "Stela Suils Cuesta"
description = "Stela is a firm believer that it’s possible to do business from the heart. She is a passionate team builder and thrives in challenging situations. Stela is a very active member of the community and organises TEDx events as well as Lean In Circles and mentorships programs. Stela is passionate about Positive Psychology, D&I, Women Empowerment and Social Entrepreneurship, specially in Blockchain and Crypto."
why_threefold = ""
function = "Co-Founder"
rank = 14
project_ids = [1,2]
contribution_ids = [1,1]
nationality = "Spanish"
