full_name = "Christophe De Carvalho Pereira Martins"
description = "Christophe is a passionate developer that likes to travel the world. Trying to improve the world around him using technology is one of his goals. He is currently working for TF Tech and is involved in the 0-OS projects among other things."
why_threefold = ""
function = "Engineer"
rank = 0
project_ids = [2,17]
contribution_ids = [3,3]
nationality = "Belgian"
