full_name = "Chris Hutton"
description = "A serial entrepreneur and technology fanatic for 25 years now. Always researching tech trends and looking for new technologies to introduce to Africa. The continent of Africa is unique, to say the least, and the issues prohibiting growth and development are unique. Africa has proven its ability to leap frog a generation in technology with the rapid adoption of mobile telecommunications and its time to bring the new internet to this continent and watch how access to information creates equality and opportunity for Africa."
why_threefold = ""
function = "Co-Founder"
rank = 0
project_ids = [1,2]
contribution_ids = [1,2]
nationality = "South African"
