full_name = "Roberto Pesce"
description = "I'm working in the Healthcare field since 30 years, with the aim of creating something useful and safe for the Community. I do feel myself as a here and now with positive attitude believer."
why_threefold = "I'm strongly convinced that a technology is really useful only when it's really at hand of everybody, all over the world. This perfectly fits the ThreeFold mission: to create a RESPONSIBLE INTERNET FOR ALL"
function = "Ambassador"
rank = 0
project_ids = [1]
contribution_ids = [2]
nationality = "Italian"
