full_name = "Evon Yacoub"
description = ""
why_threefold = "Experienced Office Manager with a demonstrated history of working in the computer software industry. Skilled in Human Resources, Management, Office Administration .. has Strong administrative professional"
function = "Office Manager"
rank = 0
project_ids = [1,8]
contribution_ids = [3,3]
nationality = "Egyptian"
