full_name = "Nickolay Babenko"
description = "Nickolay is an engineer, crypto-entrepreneur and investor and bhakti-yogi. The combination of a technical mindset and deep understanding of the psychology of relationships helps him to to achieve ambitious and practical goals and secure long-standing relationships. Having 11 years of experience in the IT industry and 4 years specifically in blockchain industry, Nickolay is eager for new opportunities to make people happier in general and with the help of technology in particular. Previously to joining GIG Technology he co-founded one of the first bitcoin payment processors and multicurrency wallets."
why_threefold = ""
function = "Co-Founder"
rank = 8
project_ids = [1,5]
contribution_ids = [1,3]
nationality = "Ukranian"
