full_name = "Adnan Fatayerji"
description = "Adnan is an international entrepreneur and part of a diverse team of innovators trying to redefine the foundation of internet.  Adnan has been based in the United Arab Emirates for the past 15 years, he has built grass root businesses and invested startups in various sectors. At Threefold he is responsible for driving operations and is honored to be part of a team that has the potential to make the world a better place by connecting billions of people to a new neutral and green internet accessible by all."
why_threefold = ""
function = "Co-Founder"
rank = 0
project_ids = [1,3,5,12,13,14,16]
contribution_ids = [1,3,3,3,3,3,3]
nationality = "American"
