full_name = "Bola E. Nasr"
description = "Software Engineer with a passion for everything new and challenging in life and technology."
why_threefold = ""
function = "Engineer"
rank = 0
project_ids = [1,8]
contribution_ids = [3,3]
nationality = "Egyptian"
