full_name = "Abdul Rehman"
description = "A dynamic hardworking individual, a dreamer, a thinker, a planner, an explorer. Never an idle day! Over 8 years of industrial experience in Telecom - IT Management and opensource technologies, particularly Telecom/VoIP, Networks, IT Systems and Support, Systems Engineering and Servers Administration."
why_threefold = ""
function = "Engineer"
project_ids = [1,5]
contribution_ids = [6,6]
nationality = "Egyptian"
