full_name = "Roel van Sabben"
description = """ An advertising art director that always had a passion for data and measuring the effects of advertising campaigns. Now Digital Marketeer at BetterToken & Threefold Foundation.Besides work you can find me out with my family or on the mats being a teacher and forever a student of the beautiful martial art Brazilian Jiu Jitsu."""
why_threefold = ""
function = "Digital Marketeer"
rank = 0
project_ids = [1,2,4]
contribution_ids = [1,3,3]
nationality = "Dutch"
