full name = ['Roel van Sabben']
why threefold = ['An advertising art director that always had a passion for data and measuring the effects of advertising campaigns. Now Digital Marketeer at BetterToken & Threefold Foundation.Besides work you can find me out with my family or on the mats being a teacher and forever a student of the beautiful martial art Brazilian Jiu Jitsu.']
function = ['Digital Promotor']
project id(s) = ['1,2,4 ']  
contribution id = ['1']
