full_name = ['Roel van Sabben']
description = ['An advertising art director that always had a passion for data and measuring the effects of advertising campaigns. Now Digital Marketeer at ThreeFold Tech & Threefold Foundation. Besides work you can find me out with my family or on the mats being a teacher and forever a student of the beautiful martial art Brazilian Jiu Jitsu.']
why_threefold = ['This project can change the world, a world in which I hope my children grow up to be empowered by the internet, not abused.']
function = ['Digital Promotor']
project_ids = ['1,2,4 ']  
contribution_ids = ['1']
