full_name = "Ahmed Thabet"
description = "Ahmed is an Electrical Engineer with great passion in Computer Science, Currently working with TF-Chain team"
why_threefold = ""
function = "Engineer"
rank = 0
project_ids = [1,8]
contribution_ids = [6,6]
nationality = "Egyptian"
