full_name = "Maxime Daniel"
description = "C, python and nodejs developer, Gentoo user, Linux and Music addict"
why_threefold = ""
function = "Engineer"
rank = 0
project_ids = [1,2]
contribution_ids = [6,6]
nationality = "Belgian"
