full_name = "Bishoy Mikhaiel"
description = "I am cloud system engineer with 6 years experience on different platform Worked with openstack and virtualization Worked as an application support on tomcat and MySQL platform and on jumpsacle and postgres Worked on DCPM racktivity application."
why_threefold = ""
function = "Engineer"
rank = 0
project_ids = [1,8]
contribution_ids = [6,6]
nationality = "Egyptian"
