full_name = "Dylan Verstraete"
description = "Full stack web engineer."
why_threefold = "I want to be a part of this digital shift."
function = "Engineer"
rank = 0
project_ids = [1,2]
contribution_ids = [6,6]
nationality = "Belgian"
