full_name = "Abdulrahman Hamdy"
description = "Software developer with a passion for fixing bugs"
why_threefold = ""
function = "Engineer"
rank = 0
project_ids = [1,8]
contribution_ids = [3,3]
nationality = "Egyptian"
