full_name = "Glen De Cauwsemaecker"
description = "Research & Develop Open Source Software"
why_threefold = ""
function = "Engineer"
rank = 0
project_ids = [1,2,3]
contribution_ids = [6,3,3]
nationality = "Belgian"
