full_name = "Sabrina Sadika"
description = "Sabrina is a jack of all trades when it comes to ThreeFold. She is the owner of the app, handles most of the customer communication, is in charge of the logistic aspects and helps out whevever needed. She's known internally as the Token Fairy. Sabrina is an outgoing person who loves to laugh and be with friends and family, but she's secretly also a bit of a nerd who loves the calmth of being alone and reading a book while her daughter is asleep. Her hobbies include reading, watching Netflix and GoT, and being a kick-ass mom."
why_threefold = ""
function = "Co-Founder"
rank = 10
project_ids = [1,2]
contribution_ids = [1,1]
nationality = "Belgian"
