full_name = "Samir Hosny"
description = "Samir is a person who has a passion for learning new technologies all the time , I got my Bachelor degree in Computer Science and then started working in the field of cloud computing since 5 years"
why_threefold = ""
function = "Engineer"
rank = 0
project_ids = [1,8]
contribution_ids = [3,3]
nationality = "Egyptian"
