full_name = "Olivia Jurado"
description = "Olivia is passionate about getting back to a manner of living that is more harmonious with nature by embracing the principles of a regenerative and slow lifestyle. It is vitally important that we make conscious decisions in our everyday life - all of our actions and choices impact the environment and fellow earthlings. We are part of nature and that is why it is our duty now to stop harming ourselves and help our planet Earth heal."
why_threefold = ""
function = "Co-Founder"
rank = 0
project_ids = [1,5,7]
contribution_ids = [1,3,1]
nationality = ""
