full_name = "Olivia Jurado"
description = "Olivia is a Co-Founder of the THREEFOLD LOVE initiative, with a mission of digital inclusion by empowering communities through the use of ThreeFold technologies.  

Olivia is an eco-socialpreneur and serial volunteer. Living each day in mindful ways in an attempt to get back to a manner of living that is more harmonious with nature, while trying  to find a balance between high tech and low tech living.

Spreading the love...into the fold."
why_threefold = ""
function = "Co-Founder"
rank = 15
project_ids = [1,5,7]
contribution_ids = [1,3,1]
nationality = ""
